import { createPagesFunctionHandler } from '@react-router/cloudflare'
import getLoadContext from '../app/getLoadContext'

// @ts-ignore - the server build file is generated by `react-router build`
import * as build from '../build/server'

export const onRequest = createPagesFunctionHandler({ build, getLoadContext })
